RealEstate/Luna_admin/urls.py
from django.conf.urls import patterns, url
from Luna_admin import views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
        url(r'^login/$', views.login, name='login'),
	 url(r'^signout/$', views.signout, name='signout'),
        url(r'^change_password/$', login_required(views.change_password), name='change_password'),
	url(r'^sendsms/$', login_required(views.send_sms), name='sendSms'),
	url(r'^sendsms/(?P<cell_no>.+)/(?P<draft_id>\d+)$', login_required(views.send_sms), name='sendSms'),
	url(r'^user_list/$', login_required(views.user_list), name='user_list'),
	url(r'^change_user_active_status/(?P<user_id>\d+)/$', login_required(views.change_user_active_status), 				name='change_user_active_status'),
	url(r'^add_edit_user/((?P<user_id>\d+)/)?$',login_required(views.add_edit_user),name='add_edit_user'),
)

RealEstate/RealEstate/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from RealEstate import view

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',

	url(r'^admin/', include('Luna_admin.urls',namespace='Luna_admin')),
	url(r'^realestate/admin/',include('RealEstate_admin.urls',namespace='RealEstate_admin')),
	url(r'^$',view.home,name='home'),
	url(r'^search$',view.search,name='search'),
	url(r'^detail/(?P<file_id>\d+)/$',view.property_detail,name='detail'),
	url(r'^contact_us$',view.contact_us,name='contact_us'),
	url(r'^about_us$',view.about_us,name='about_us'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

RealEstate/RealEstate_admin/urls.py
from django.conf.urls import patterns, url
from RealEstate_admin import files, home, end_deals, special_files
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
                       #admin home page
                       url(r'^$', login_required(home.index), name='home'),
                       # show ending deals
                       url(r'^enddeals/$', login_required(end_deals.get_deals), name="endDeals"),
                       #add new file
                       url(r'^files$', login_required(files.index), name='fileIndex'),
                       url(r'^addnewfile$', login_required(files.add_new_file), name='addNewFile'),
                       #edit file
                       url(r'^editfile/(?P<file_id>\d+)/deal', login_required(files.edit_file_deal),
                           name='editFileDeal'),
                       url(r'^editfile/editdeal$', login_required(files.edit_deal), name='editDeal'),
                       url(r'^editfile/(?P<file_id>\d+)/detail', login_required(files.edit_file_detail),
                           name='editFileDetail'),
                       url(r'^enddeal/$', login_required(files.end_deal), name='endDeal'),
                       url(r'^addnewDeal/$', login_required(files.add_new_deal), name='addNewDeal'),
                       url(r'^editfile/editownerdetail$', login_required(files.edit_detail_owner),
                           name='editOwnerDetail'),
                       url(r'^editfile/editpropertydetail$', login_required(files.edit_detail_property_detail),
                           name='editPropertyDetail'),
                       url(r'^editfile/editotherpropertydetail$', login_required(files.edit_detail_other_detail),
                           name='editOtherPropertyDetail'),
                       url(r'^editfile/(?P<file_id>\d+)/options', login_required(files.edit_file_options),
                           name='editFileOptions'),
                       url(r'^editfile/(?P<file_id>\d+)/editoptions$', login_required(files.edit_options),
                           name='editOptions'),
                       url(r'^editfile/(?P<file_id>\d+)/images', login_required(files.edit_file_images),
                           name='editFileImages'),
                       url(r'^delete_image/(?P<file_id>\d+)/(?P<image_id>\d+)/$', login_required(files.delete_image),
                           name='delete_image'),
                       url(r'^editfile/(?P<file_id>\d+)/options', login_required(files.edit_file_options),
                           name='editFileOptions'),
                       url(r'^matched_files_requests/$', login_required(files.matched_files_requests),
                           name='matchedFilesRequests'),
                       #property request
                       url(r'^property_requests$', login_required(files.property_request_index),
                           name='propertyRequests'),
                       url(r'^add_edit_request/((?P<property_request_id>\d+)/)?$',
                           login_required(files.add_edit_property_request), name='addEditPropertyRequest'),
                       url(r'^delete_property_request/(?P<property_request_id>\d+)/$',
                           login_required(files.delete_property_request), name='deletePropertyRequest'),
                       url(r'^contact_us$', login_required(files.list_contact_us), name='contactUs'),
                       url(r'^delete_contact/(?P<contact_id>\d+)/$', login_required(files.delete_contact),
                           name='deleteContact'),
                       #special deals
                       url(r'^special_deals/$', login_required(special_files.special_files), name='special'),
                       url(r'^delete_special/(?P<file_id>\d+)/$', login_required(special_files.delete),
                           name='delete_special'),

                       #profile
                       url(r'^profile/$', login_required(files.add_edit_profile),
                           name='add_edit_profile'),
                       )

RealEstate/Luna_admin/models.py
from django.db import models
from django.contrib.auth.models import User

# Sms Model
class SmsLog(models.Model):
	sender_no = models.CharField(max_length=11)
	text = models.CharField(max_length=1000)
	send_date = models.DateField(auto_now_add=True)
	user = models.ForeignKey(User)

RealEstate/Luna_admin/forms.py
from django import forms

class SendSmsForm(forms.Form):
	sender_no = forms.CharField(max_length=1000)
	text = forms.CharField(max_length=1000)


class UserRegistrationForm(forms.Form):
	use_id=forms.HiddenInput()
	first_name = forms.CharField(max_length=100,required=False)
	last_name = forms.CharField(max_length=100,required=False)
 	username = forms.CharField(max_length=100)
	password = forms.CharField(max_length=100)
	password_repeat = forms.CharField(max_length=100)

RealEstate/Luna_admin/views.py
#! /usr/bin/env python
# -*- coding: utf8 -*-

from RealEstate import settings
from django.shortcuts import render,get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.contrib.auth import authenticate, logout, login as auth_login
from django.template import RequestContext
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect
from Luna_admin.models import SmsLog
from Luna_admin.forms import SendSmsForm, UserRegistrationForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import PermissionDenied
from django.db import models
from SOAPpy import WSDL

# Create your views here.

def login(request):
    username = password = ''
    if request.POST:
    	username = request.POST.get('username')
        password = request.POST.get('password')
        u = authenticate(username=username, password=password)
       	if u :
            	auth_login(request, u)
	    	messages.add_message(request, messages.SUCCESS, 'شما با موفقیت وارد سیستم شده اید.')
		return HttpResponseRedirect(reverse('RealEstate_admin:home'))
       	else:
           	messages.add_message(request, messages.ERROR, 'نام کاربری یا رمز عبور اشتباه است.')
		return render_to_response('Luna_admin/login.html',{'username':username}, context_instance=RequestContext(request))
    else:
    	return render_to_response('Luna_admin/login.html',RequestContext(request))# context_instance=RequestContext(request))

def signout(request):
	logout(request)
	url = reverse('home',args=(),kwargs=())
        return HttpResponseRedirect(url) 

def change_password(request):
    if request.POST:
        old_pass = request.POST.get('old_pass')
        new_pass = request.POST.get('new_pass')
        repeat_new_pass = request.POST.get('repeat_new_pass')
        user = authenticate(username=request.user.username, password=old_pass)        
        if user is not None: 
		if not new_pass or not repeat_new_pass :
			messages.add_message(request, messages.ERROR, 'گذرواژه جدید و تکرار آن را وارد کنید.')     
		elif new_pass != repeat_new_pass:
			messages.add_message(request, messages.ERROR, 'گذرواژه جدید با تکرار آن یکسان نیست.')
		else:
                    user.set_password(new_pass)
	            user.save()
		    messages.add_message(request, messages.SUCCESS, 'تغییر گذرواژه با موفقیت انجام شد.')
        else:
	    messages.add_message(request, messages.ERROR, 'گذرواژه اشتباه است.')   
	return render_to_response('Luna_admin/change_password.html',{'username':request.user.username}, 				context_instance=RequestContext(request))   
            
    return render_to_response('Luna_admin/change_password.html', context_instance=RequestContext(request))	
    
def send_sms(request, cell_no=None, draft_id=None):
	if request.method == 'POST':
		form=SendSmsForm(request.POST)
		if form.is_valid():
			_server = None
			remaining_credit = None
			text = form.cleaned_data['text']
			sender_no = form.cleaned_data['sender_no']
			_sender_no_parts = sender_no.split('-')
			try:
				user = request.user
				_server = WSDL.Proxy(settings.SMS_WEB_SERVICE_URL)
				for cell_no in _sender_no_parts:
					 								
					_result = _server.SendSMS(settings.SMS_USERNAME, 							settings.SMS_PASSWORD,cell_no,text,settings.SMS_SENDER_NO)
					if(len(_result) >= 8):
						messages.add_message(request, messages.SUCCESS, u"پیامک به شماره %s ارسال شد." % cell_no) 
						sms_log = SmsLog(sender_no=cell_no,text=text, user=user)
						sms_log.save()

						
					elif _result == 12 or _result == -3:
						messages.add_message(request, messages.ERROR, 'میزان اعتبار شما به اتمام رسیده است.لطفا آن را تمدید کنید.')  
					elif _result == 20:
						messages.add_message(request, messages.ERROR, 'متن پیامک طولانی است.')  
					elif _result == 23:
						messages.add_message(request, messages.ERROR, 'تعداد دریافت کنندگان بیش از حد مجاز است.')
					else: 						
						messages.add_message(request, messages.ERROR, 'خطا در ارسال پیامک.')				
			except:
				messages.add_message(request, messages.ERROR, 'خطا در ارسال پیامک. لطفا مجددا ارسال کنید.') 
			#remaining_credit = get_remaining_sms_credit(_server)
		url = reverse('Luna_admin:sendSms',args=(),kwargs=())
        	return HttpResponseRedirect(url)
				
		#return HttpResponseRedirect("../admin/sendsms")
						
			
	else:
		form = SendSmsForm()
		default_text = ''
		if draft_id:
			if draft_id == '1':
				default_text = "فایل شما در سیستم ثبت شد."
			elif draft_id == '2' :
				default_text = "قرارداد شما در حال اتمام است."

		remaining_credit = get_remaining_sms_credit()

		sms = {'cell_no' : cell_no, 'default_text' : default_text}
		return render_to_response(
			'Luna_admin/send_sms.html',
		        {'sms':sms, 'form':form, 'remaining_credit': remaining_credit},
		        context_instance=RequestContext(request)
			)

def user_list(request):
	if not request.user.is_superuser :
		raise PermissionDenied
	users = User.objects.filter(is_superuser=False).order_by("-date_joined")
	paginator = Paginator(users, 25)
	page = request.GET.get('page')
	try:
		users_page=paginator.page(page)
		return render(request,'Luna_admin/user_list.html',{'users':users_page})
	except PageNotAnInteger:
		users_page=paginator.page(1)
		return render(request,'Luna_admin/user_list.html',{'users':users_page})
	except EmptyPage:
		return render(request,'Luna_admin/user_list.html')

def change_user_active_status(request, user_id):
	if not request.user.is_superuser :
		raise PermissionDenied
	user = get_object_or_404(User, id=user_id)	
	user.is_active = not user.is_active
	user.save()
	if user.is_active:
		messages.add_message(request, messages.SUCCESS, 'کاربر فعال شد.')
	else:
		messages.add_message(request, messages.SUCCESS, 'کاربر غیر فعال شد.')
	url = reverse('Luna_admin:user_list',args=(),kwargs=())
        return HttpResponseRedirect(url)

def add_edit_user(request, user_id) :
	if not request.user.is_superuser :
		raise PermissionDenied
	if request.method == 'POST':
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			#u_id = request.POST.get('use_id')
			user = ''
			password = form.cleaned_data['password']
			password_repeat = form.cleaned_data['password_repeat']
			if password != password_repeat:
		        	messages.add_message(request, messages.ERROR, 'گذرواژه با تکرار آن یکسان نیست.')
			else:
				
				'''if u_id != 'None':
					user = get_object_or_404(User,id=int(u_id))
					user.first_name = form.cleaned_data['first_name']
					user.last_name = form.cleaned_data['last_name']
					user.username = form.cleaned_data['username']
					user.password = form.cleaned_data['password']
					user.is_superuser = False
					user.is_staff = True'''
			
				#else:
				user = User(
					first_name = form.cleaned_data['first_name'],
					last_name = form.cleaned_data['last_name'],
					username = form.cleaned_data['username'],
					is_superuser = False,
					is_staff = True
						)
			
				try:	
					user.set_password(form.cleaned_data['password'])				
					user.save()
					messages.add_message(request, messages.SUCCESS, 'تغییرات اعمال شد.')
				except:
					 messages.add_message(request, messages.ERROR, 'نام کاربری تکراری است. لطفا آن را تغییر دهید.')   	
			#if u_id != 'None':
			#	return HttpResponseRedirect(
			#		'../add_edit_user/{}/'.format(u_id),{'user':user})
			#else:
			return render_to_response(
				'Luna_admin/add_edit_user.html',
		        	context_instance=RequestContext(request))
		#return render_to_response(
					#'Luna_admin/add_edit_user.html',{'form': form},
		        		#context_instance=RequestContext(request))
	else:
		 '''if user_id :
		 	user = get_object_or_404(User,id=user_id)
			return render_to_response(
        		'Luna_admin/add_edit_user.html',{'user':user},
                	context_instance=RequestContext(request))
		 else:'''
		 return render_to_response(
			 'Luna_admin/add_edit_user.html',
			 context_instance=RequestContext(request))

RealEstate/Luna_admin/templates/Luna_admin/add_edit_user.html
{% extends "Luna_admin/admin_master.html" %} 
{% load staticfiles %}
{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'Luna_admin/style/Login/index.css' %}" />
{% endblock %}
{% block body_script %}
	<script type='text/javascript' src="{% static 'Luna_admin/script/user/add_edit_user.js' %}"></script>
{% endblock %}
{% block content %}




 <div id="userFormErrors"></div>

        <div class="form_head"><span class="icon glyphicon glyphicon-repeat"></span>ثبت کاربر</div>
<form class="form-horizontal" id="userForm" name="userForm" action="{% url 'Luna_admin:add_edit_user'%}" method="post">
{% csrf_token %}
<input type="hidden" value="{{user.id}}" name="use_id" id="use_id" />
<div class="control-group">
<label class="control-label" for="first_name">نام</label>
<div class="controls">
<input type="text" id="first_name" name="first_name" value="{{user.first_name}}"  placeholder="نام" class = "form-control">
</div>
</div>

<div class="control-group">
<label class="control-label" for="last_name">نام خانوادگی</label>
<div class="controls">
<input type="text" id="last_name" name="last_name" value="{{user.last_name}}"  placeholder="نام خانوادگی" class = "form-control">
</div>
</div>

<div class="control-group">
<label class="control-label" for="username">نام کاربری</label>
<div class="controls">
<input type="text" id="username" name="username" value="{{user.username}}"  placeholder="نام کاربری" class = "form-control">
</div>
</div>

<div class="control-group">
<label class="control-label" for="password">گذرواژه</label>
<div class="controls">
<input type="password" name="password" id="password" placeholder="گذرواژه" class = "form-control">
</div>
</div>
<div class="control-group">
<label class="control-label" for="password_repeat">تکرار گذرواژه</label>
<div class="controls">
<input type="password" name="password_repeat" id="password_repeat" placeholder="تکرار گذرواژه" class = "form-control">
</div>
</div>
<div class="control-group">
<div class="controls">
<button type="submit" class="btn btn-primary">ثبت تغییرات</button>
</div>
</div>

</form>
<div class="control-group" style="float:left;">
<div class="controls">
<a href="{% url 'Luna_admin:user_list'%}">
<button class="btn btn-primary">بازگشت به مدیریت کاربران</button>
</a>
</div>
</div>
 {% endblock %} 

RealEstate/Luna_admin/templates/Luna_admin/admin_master.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block page_title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	{# style #}
		<link rel="stylesheet" type="text/css" href="{% static 'Luna_admin/style/bootstrap-rtl.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'Luna_admin/style/master_style.css' %}" />
		{% block style %}{% endblock %}
	{# /style #}

	{# head scripts #}
		<script type='text/javascript' src="{% static 'Luna_admin/script/respond.js' %}"></script>
		{% block head_script %}{% endblock %}
	{# /head scripts #}

</head>
<body>

	<div class="navbar navbar-inverse navbar-fixed-top TopMenu" role="navigation">
		<div class="">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			<a class="navbar-brand logo" href="#">LUNASOFT</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class=""><a href="{% url 'RealEstate_admin:home' %}">خانه</a></li>
					<li><a href="{% url 'RealEstate_admin:fileIndex' %}">مديريت فايل ها</a></li>
					<li><a href="{% url 'RealEstate_admin:endDeals' %}">معامله های در حال اتمام</a></li>
					<li class=""><a href="{% url 'RealEstate_admin:propertyRequests' %}">مدیریت درخواستها</a></li>
					<li><a href="{% url 'Luna_admin:user_list' %}">مديريت کاربران</a></li>
					<li><a href="{% url 'Luna_admin:sendSms' %}">مدیریت SMS</a></li>
					<li><a href="{% url 'RealEstate_admin:contactUs' %}">درخواستهای مشاوره</a></li>
					<li><a href="{% url 'RealEstate_admin:add_edit_profile' %}">مشخصات بنگاه</a></li>
				</ul>
			</div>
		</div>
	</div>

	<div class="shortcutMenu">
		<ul class="nav nav-pills">
			<li><a href="#">
				<span class="glyphicon glyphicon-user"></span>کاربر  : {{request.user.username}}
				
			</a></li>
			<li><a href="{% url 'Luna_admin:change_password' %}">
				<span class="glyphicon glyphicon-repeat"></span>تغییر گذرواژه
			</a></li>
			<li><a href="{% url 'Luna_admin:signout' %}">
				<span class="glyphicon glyphicon-off"></span>خروج
			</a></li>
		</ul>
	</div>
	<div class="container content">

	<div class="title"><span class="'glyphicon glyphicon-list-alt'"></span> {% block content_title %}{% endblock %}
    </div>
	{% if messages %}
           {% for message in messages %}
           
              <div {% if message.tags %} class="{{ message.tags }}"{% endif %} >
              {% ifequal message.tags 'error' %}
              	<span class='glyphicon glyphicon-remove'></span>
              {% else %}
              	<span class='glyphicon glyphicon-ok'></span>
              {% endifequal %}
              	{{ message }}
              </div>
           {% endfor %}
        {% endif %}
	{# main container #}
		{% block content %}	{% endblock %}
	{# /main container #}
	</div>

<div class="copyright">
			کلیه حقوق این سامانه متعلق به گروه توسعه نرم افزار 	<a href="http://www.lunasoft.ir" target="_blank">لونا سافت</a> می باشد .  2014&copy; <img src="{%static 'style/img/LunaLogo.png'%}" alt="luna" />
		</div>
	{# body scripts #}
		<script type='text/javascript' src="{% static 'Luna_admin/script/jquery-1.10.2.min.js' %}"></script>
		<script type='text/javascript' src="{% static 'Luna_admin/script/bootstrap-rtl.js' %}"></script>
		<script type='text/javascript' src="{% static 'Luna_admin/script/validate.js' %}"></script>
		{% block body_script %}{% endblock %}
	{# /body scripts #}
</body>
</html>

RealEstate/Luna_admin/templates/Luna_admin/change_password.html
{% extends "Luna_admin/admin_master.html" %} 
{% load staticfiles %}
{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'Luna_admin/style/Login/index.css' %}" />
{% endblock %}
{% block body_script %}
	<script src="{% static 'Luna_admin/script/user/change_password.js' %}"></script>
{% endblock %}
{% block content %}

 <div>
        <div class="form_head"><span class="icon glyphicon glyphicon-repeat"></span>تغییر گذرواژه</div>
<div id="changePassFormErrors"> </div>
<form class="form-horizontal" id="changePassForm" name="changePassForm" action="{% url 'Luna_admin:change_password' %}" method="post">
{% csrf_token %}

<div class="control-group">
<label class="control-label" for="old_pass">گذرواژه قبلی</label>
<div class="controls">
<input type="password" name="old_pass" id="old_pass" placeholder="گذرواژه قبلی" class = "form-control">
</div>
</div>
<div class="control-group">
<label class="control-label" for="new_pass">گذرواژه جدید</label>
<div class="controls">
<input type="password" name="new_pass" id="new_pass" placeholder="گذرواژه جدید" class = "form-control">
</div>
</div>
<div class="control-group">
<label class="control-label" for="repeat_new_pass">تکرار گذرواژه جدید</label>
<div class="controls">
<input type="password" name="repeat_new_pass" id="repeat_new_pass" placeholder="تکرار گذرواژه جدید" class = "form-control">
</div>
</div>
<div class="control-group">
<div class="controls">
<button type="submit" class="btn btn-primary">تغییر گذرواژه</button>
</div>
</div>
</form>
</div>
 {% endblock %} 

RealEstate/Luna_admin/templates/Luna_admin/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<title>ورود به مدیریت</title>
		<link rel="stylesheet" type="text/css" href="{% static 'Luna_admin/style/bootstrap-rtl.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'Luna_admin/style/Login/index.css' %}" />
	</head>
	<body>
	 <div class="container content">
        <div class="form_head"><span class="icon glyphicon glyphicon-log-in"></span>ورود به مدیریت</div>
{% if messages %}
           {% for message in messages %}
           
              <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% ifequal message.tags 'error' %}
              	<span class='glyphicon glyphicon-remove'></span>
              {% else %}
              	<span class='glyphicon glyphicon-ok'></span>
              {% endifequal %}
              	{{ message }}
              </div>
           {% endfor %}
        {% endif %}
<form class="form-horizontal" name="Login" id="Login" action="{% url 'Luna_admin:login' %}" method="post">
{% csrf_token %}
<div class="control-group">
<label class="control-label" for="username">نام کاربری</label>
<div class="controls">
<input type="text" id="username" name="username" value="{{username}}" placeholder="" class = "form-control">
</div>
</div>
<div class="control-group">
<label class="control-label" for="password">گذرواژه</label>
<div class="controls">
<input type="password" name="password" id="password"  placeholder="" class = "form-control">
</div>
</div>
<div class="control-group">
<div class="controls" style="margin-top:15px;margin-bottom:15px;direction:ltr">
<button type="submit" class="btn btn-primary " style="width:100px;"> ورود </button>
</div>
</div>
</form>
</div>
 	</body>
  </html>

RealEstate/Luna_admin/templates/Luna_admin/send_sms.html
{% extends "Luna_admin/admin_master.html" %}
{% load staticfiles %}
{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'Luna_admin/style/sms/index.css' %}" />
{% endblock %}
{% block body_script %}
	<script  src="{% static 'Luna_admin/script/validate.js' %}"></script>
	<script src="{% static 'Luna_admin/script/sms/sendsms.js' %}"></script>
{% endblock %}
        {% block page_title %}{% block content_title %}ارسال پیامک {% endblock %}{% endblock %}
{% block content %}

<div>
        <div class="form_head"><span class="icon glyphicon glyphicon-phone"></span>ارسال پیامک </div>
         {% if remaining_credit %}
        <div> 
        	اعتبار باقیمانده:  {{ remaining_credit }} ریال
        </div>
        {% endif %}
<div id="sendSmsFormErrors"></div>
<form class="form-horizontal" id="sendSmsForm" name="sendSmsForm" role="form" method="POST" action="{% url 'Luna_admin:sendSms' %}">
   {% csrf_token %}
    
   <div class="control-group">
                <label for="sender_no" class="control-label">شماره های ارسال <span class="required">*</span></label>
                <div class="controls">
                    <textarea class="form-control" id="sender_no" name="sender_no">{{sms.cell_no|default_if_none:''}}</textarea>
                   
                </div>
    </div>

   
   
            <div class="control-group">
                <label for="text" class="control-label">متن پیامک <span class="required">*</span></label>
                <div class="controls">
                    <textarea class="form-control" name="text" id="text">{{sms.default_text|default_if_none:''}}</textarea>
                </div>
                <div id="remainingChars"></div>
            	</div>
        </div>

 

  
    <div class="control-group">
<div class="controls">
        <button id="sendSmsBtn" type="submit" class="btn btn-primary">ارسال پیامک</button>
   </div>
</div>
</form>
</div>
 {% endblock %} 

RealEstate/Luna_admin/templates/Luna_admin/user_list.html
{% extends "Luna_admin/admin_master.html" %}
{% load staticfiles %}
{% load luna_filters %}
{% block page_title %}{% block content_title %}مدیریت کاربران{% endblock %}{% endblock %}
{% block body_script %}
	<script  src="{% static 'Luna_admin/script/validate.js' %}"></script>
{% endblock %}
{% block content %}

<div class="thumbnail">
	{% if not users %}
		<p class="notFind"><span class="glyphicon glyphicon-minus"></span>کاربری ثبت نشده است</p>
	{% else %}
        <table class="table table-responsive table-striped table-hover">
            <thead>
                <tr><td>نام کاربری</td><td>نام</td><td>نام خانوادگی</td><td>تاریخ ثبت کاربر</td><td>آخرین ورود به سیستم</td><td>تغییر وضعیت کاربر</td></tr>
            </thead>
            <tbody>
			{% for user in users %}
			  <tr><td>{{user.username}}</td><td>{{user.first_name}}</td><td>{{user.last_name}}</td><td>{{user.date_joined| persian_date}}</td><td>{{user.last_login| persian_date}}</td>



<form class="form-horizontal" method="POST" action="{% url 'Luna_admin:change_user_active_status' user.id %}">
{% csrf_token %}
			  <td>
				
				 <button style="background-color:transparent;border:none;color:blue;">
					{% if user.is_active %}
						<span class="glyphicon glyphicon-remove"></span>
					{% else %}
						<span class="glyphicon glyphicon-ok"></span>
					{% endif %}
			 	</button>
			  </td>

</form>




</tr>
			{% endfor %}
            </tbody>
        </table>
  <ul class="pagination">
		 {% if users.has_previous %}
			<li><a href="?page={{ users.previous_page_number }}"><</a></li>
        {% endif %}

        <li class="active"><a href=#>
            صفحه {{ users.number }} از {{ users.paginator.num_pages }}
        </a></li>

        {% if users.has_next %}
            <li><a href="?page={{ users.next_page_number }}">></a></li>
        {% endif %}
       
</ul>
	{% endif %}

</div>
{% comment %} ثبت کاربر جدید{% endcomment %}
 
<div class="">
  <a href="{% url 'Luna_admin:add_edit_user' %}">
    <button type="button" class="btn btn-primary btn-sm "><span class="glyphicon glyphicon-plus"></span>ثبت کاربر جدید</button>
   </a>
</div>






{% endblock %}