RealEstate/Luna_admin/urls.py
from django.conf.urls import patterns, url
from Luna_admin import views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
        url(r'^login/$', views.login, name='login'),
	 url(r'^signout/$', views.signout, name='signout'),
        url(r'^change_password/$', login_required(views.change_password), name='change_password'),
	url(r'^sendsms/$', login_required(views.send_sms), name='sendSms'),
	url(r'^sendsms/(?P<cell_no>.+)/(?P<draft_id>\d+)$', login_required(views.send_sms), name='sendSms'),
	url(r'^user_list/$', login_required(views.user_list), name='user_list'),
	url(r'^change_user_active_status/(?P<user_id>\d+)/$', login_required(views.change_user_active_status), 				name='change_user_active_status'),
	url(r'^add_edit_user/((?P<user_id>\d+)/)?$',login_required(views.add_edit_user),name='add_edit_user'),
)

RealEstate/RealEstate/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from RealEstate import view

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',

	url(r'^admin/', include('Luna_admin.urls',namespace='Luna_admin')),
	url(r'^realestate/admin/',include('RealEstate_admin.urls',namespace='RealEstate_admin')),
	url(r'^$',view.home,name='home'),
	url(r'^search$',view.search,name='search'),
	url(r'^detail/(?P<file_id>\d+)/$',view.property_detail,name='detail'),
	url(r'^contact_us$',view.contact_us,name='contact_us'),
	url(r'^about_us$',view.about_us,name='about_us'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

RealEstate/RealEstate_admin/urls.py
from django.conf.urls import patterns, url
from RealEstate_admin import files, home, end_deals, special_files
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
                       #admin home page
                       url(r'^$', login_required(home.index), name='home'),
                       # show ending deals
                       url(r'^enddeals/$', login_required(end_deals.get_deals), name="endDeals"),
                       #add new file
                       url(r'^files$', login_required(files.index), name='fileIndex'),
                       url(r'^addnewfile$', login_required(files.add_new_file), name='addNewFile'),
                       #edit file
                       url(r'^editfile/(?P<file_id>\d+)/deal', login_required(files.edit_file_deal),
                           name='editFileDeal'),
                       url(r'^editfile/editdeal$', login_required(files.edit_deal), name='editDeal'),
                       url(r'^editfile/(?P<file_id>\d+)/detail', login_required(files.edit_file_detail),
                           name='editFileDetail'),
                       url(r'^enddeal/$', login_required(files.end_deal), name='endDeal'),
                       url(r'^addnewDeal/$', login_required(files.add_new_deal), name='addNewDeal'),
                       url(r'^editfile/editownerdetail$', login_required(files.edit_detail_owner),
                           name='editOwnerDetail'),
                       url(r'^editfile/editpropertydetail$', login_required(files.edit_detail_property_detail),
                           name='editPropertyDetail'),
                       url(r'^editfile/editotherpropertydetail$', login_required(files.edit_detail_other_detail),
                           name='editOtherPropertyDetail'),
                       url(r'^editfile/(?P<file_id>\d+)/options', login_required(files.edit_file_options),
                           name='editFileOptions'),
                       url(r'^editfile/(?P<file_id>\d+)/editoptions$', login_required(files.edit_options),
                           name='editOptions'),
                       url(r'^editfile/(?P<file_id>\d+)/images', login_required(files.edit_file_images),
                           name='editFileImages'),
                       url(r'^delete_image/(?P<file_id>\d+)/(?P<image_id>\d+)/$', login_required(files.delete_image),
                           name='delete_image'),
                       url(r'^editfile/(?P<file_id>\d+)/options', login_required(files.edit_file_options),
                           name='editFileOptions'),
                       url(r'^matched_files_requests/$', login_required(files.matched_files_requests),
                           name='matchedFilesRequests'),
                       #property request
                       url(r'^property_requests$', login_required(files.property_request_index),
                           name='propertyRequests'),
                       url(r'^add_edit_request/((?P<property_request_id>\d+)/)?$',
                           login_required(files.add_edit_property_request), name='addEditPropertyRequest'),
                       url(r'^delete_property_request/(?P<property_request_id>\d+)/$',
                           login_required(files.delete_property_request), name='deletePropertyRequest'),
                       url(r'^contact_us$', login_required(files.list_contact_us), name='contactUs'),
                       url(r'^delete_contact/(?P<contact_id>\d+)/$', login_required(files.delete_contact),
                           name='deleteContact'),
                       #special deals
                       url(r'^special_deals/$', login_required(special_files.special_files), name='special'),
                       url(r'^delete_special/(?P<file_id>\d+)/$', login_required(special_files.delete),
                           name='delete_special'),

                       #profile
                       url(r'^profile/$', login_required(files.add_edit_profile),
                           name='add_edit_profile'),
                       )

RealEstate/RealEstate_admin/forms.py
#! /usr/bin/env python
# -*- coding: utf8 -*-
"""
@author: AR.Jozaghi
@organization: LunaSoft
@copyright: Copyright © 2014 LUNA
@license:
@contact:
"""
from django import forms
from django.forms import ModelForm
from RealEstate_admin import models


class AddNewFileForm(forms.Form):
    owner_name = forms.CharField(max_length=100, required=False)
    owner_family = forms.CharField(max_length=100)
    owner_cell = forms.CharField(max_length=11)
    area = forms.CharField(max_length=100)
    property_type = forms.CharField(max_length=20)
    other_property_type_name = forms.CharField(max_length=100, required=False)
    deal_type = forms.CharField(max_length=20)
    masahat_kol = forms.IntegerField(required=False)
    total_price = forms.IntegerField(required=False)
    rahne_kamel_price = forms.IntegerField(required=False)
    rahn_price = forms.IntegerField(required=False)
    ejare_price = forms.IntegerField(required=False)
    address = forms.CharField(max_length=200)
    is_synced = forms.BooleanField(required=False)


class EditDealForm(forms.Form):
    deal_type = forms.CharField(max_length=20)
    bazdid_type = forms.CharField(max_length=20)
    name_mostajer_ya_negahban = forms.CharField(max_length=200, required=False)
    tell_mostajer_ya_negahban = forms.CharField(max_length=20, required=False)
    tarikhe_takhliye = forms.CharField(max_length=12, required=False)
    total_price = forms.IntegerField(required=False)
    meter_price = forms.IntegerField(required=False)
    rahne_kamel_price = forms.IntegerField(required=False)
    rahn_price = forms.IntegerField(required=False)
    ejare_price = forms.IntegerField(required=False)
    ghabel_tabdil = forms.CharField(max_length=100, required=False)
    charge_price = forms.IntegerField(required=False)
    deal_id = forms.IntegerField()
    file_id = forms.IntegerField()
    is_synced = forms.BooleanField(required=False)


class EditOwnerDetailForm(forms.Form):
    owner_name = forms.CharField(max_length=100)
    owner_family = forms.CharField(max_length=100)
    owner_tell = forms.CharField(max_length=11, required=False)
    owner_cell = forms.CharField(max_length=20)
    file_id = forms.IntegerField()


class EditPropertyDetailForm(forms.Form):
    property_type = forms.CharField(max_length=20)
    other_property_type_name = forms.CharField(max_length=200, required=False)
    usage_type = forms.CharField(max_length=20)
    other_usage_type_name = forms.CharField(max_length=200, required=False)
    address = forms.CharField(max_length=200, required=False)
    area = forms.CharField(max_length=100)
    no_bedrooms = forms.IntegerField(required=False)
    no_floor = forms.CharField(max_length=50, required=False)
    floors = forms.CharField(max_length=50, required=False)
    tedade_vahed = forms.CharField(max_length=50, required=False)
    masahat_zamin = forms.IntegerField(required=False)
    masahat_kol = forms.IntegerField()
    zirbana = forms.IntegerField(required=False)
    ToolBar = forms.IntegerField(required=False)
    file_id = forms.IntegerField()
    property_detail_id = forms.IntegerField()


class EditOtherPropertyDetailForm(forms.Form):
    file_id = forms.IntegerField()
    property_detail_id = forms.IntegerField()
    zabete_sakht = forms.CharField(max_length=100, required=False)
    sene_bana = forms.IntegerField(required=False)
    mogheiyat = forms.CharField(max_length=100, required=False)
    noe_sanad = forms.CharField(max_length=100, required=False)
    noe_saghf = forms.CharField(max_length=100, required=False)
    vame_banki = forms.CharField(max_length=100, required=False)
    nama = forms.CharField(max_length=100, required=False)
    view_ya_manzare = forms.CharField(max_length=100, required=False)


class EditPropertyOptionForm(forms.Form):
    sarmayesh = forms.CharField(max_length=500, required=False)
    garmayesh = forms.CharField(max_length=500, required=False)
    kaf_saloon = forms.CharField(max_length=500, required=False)
    kaf_khabha = forms.CharField(max_length=500, required=False)
    badane_divar = forms.CharField(max_length=500, required=False)

    tozihat = forms.CharField(max_length=1000, required=False)
    mahvare_markazi = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    internet_wireless = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    jarubarghi_markazi = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    shooting_zobale = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    salon_ejtemaat = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    liting = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    estakhr = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    sona = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    jakuzi = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    salon_varzesh = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    roof_garden = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    barbecu = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    elam_harigh = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    etfa_harigh = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    ab_taht_feshar = forms.BooleanField(required=False, widget=forms.CheckboxInput())

    kabinet = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    gaaz_va_fer_tookar = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    Open = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    iphone = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    parde = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    komod = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    looster = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    shoomine = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    master = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    kabin_doosh = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    noorpardazi = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    noorgir_pasiyo = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    tras = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    anbari = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    parking = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    asansor = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    darb_automatik = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    vorudi_zed_serghat = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    hayate_ekhtesasi = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    labi = forms.BooleanField(required=False, widget=forms.CheckboxInput())


class PictureForm(forms.Form):
    pic = forms.FileField(label='انتخاب فایل :')
    caption = forms.CharField(max_length=100, required=False)

class PropertyRequestForm(forms.Form):
    property_request_id = forms.IntegerField(required=False)
    name = forms.CharField(max_length=100, required=False)
    family = forms.CharField(max_length=100, required=False)
    phone_no = forms.CharField(max_length=20, required=False)
    total_price = forms.IntegerField(required=False)
    rahne_kamel_price = forms.IntegerField(required=False)
    rahn_price = forms.IntegerField(required=False)
    ejare_price = forms.IntegerField(required=False)
    property_type = forms.CharField(max_length=20)
    other_property_type_name = forms.CharField(max_length=200, required=False)
    deal_type = forms.CharField(max_length=20)
    area = forms.CharField(max_length=100, required=False)
    description = forms.CharField(max_length=1000, required=False)

class EndDealForm(forms.Form):
    end_deal_date = forms.CharField(max_length=100, required=False)
    deal_name = forms.CharField(max_length=100, required=False)
    deal_family = forms.CharField(max_length=100, required=False)
    deal_cell = forms.CharField(max_length=100, required=False)
    deal_description = forms.CharField(max_length=300, required=False)
    file_id = forms.IntegerField()
    deal_id = forms.IntegerField()


class AddNewDealForm(forms.Form):
    file_id = forms.IntegerField()


class ContactUsForm(forms.Form):
    title = forms.CharField(max_length=100, required=False)
    name = forms.CharField(max_length=100, required=False)
    main_text = forms.CharField(max_length=1000)
    phone_no = forms.CharField(max_length=20, required=False)


class AddSpecialDealForm(forms.Form):
    file_code = forms.CharField()


class AddNewProfileForm(ModelForm):
    class Meta:
        model = models.Profile

RealEstate/RealEstate_admin/views.py
from django.shortcuts import render

# Create your views here.

RealEstate/RealEstate_admin/templates/RealEstate_admin/file/edit_file_images.html
{% extends "Luna_admin/admin_master.html" %}
{% load staticfiles %}
{% block page_title %}{% block content_title %}{{ editable_file }}{% endblock %}{% endblock %}
{% block body_script %}
	<script  src="{% static 'RealEstate_admin/script/file/image.js' %}"></script>
{% endblock %}
{% block content %}

<div class="row">
<div id="uploadFormErrors"></div>
    <div class="col-sm-3">
     {% include "RealEstate_admin/file/edit_file_menu_include.html" %} 
    </div>

  <form name="uploadForm" action="{% url 'RealEstate_admin:editFileImages' editable_file.pk %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
		<input type="hidden" value="{{editable_file.pk}}" name="file_id" />
    	<div class="col-sm-3">
    	<label for="caption" class="control-label">زیرنویس</label>
            <input type="text" name="caption">
        </div>
		
		<div class="col-sm-3">
		
				
				{{ form.pic }}
		
	    </div>
	    <div>
			<input type="submit"  class=" btn btn-default" value="بارگذاری عکس" />
	    </div>
						
	</form>
 </div>
 <div class="row">
<div class="col-sm-9 col-md-offset-3">	
{% if pictures %}
			<ul style="display:inline">
			{% for picture in pictures %}
				<li style="list-style:none;display:inline;margin:20px;">
					<a title="حذف تصویر" href="{% url 'RealEstate_admin:delete_image' editable_file.pk picture.id  %}">
<span class="glyphicon glyphicon-trash"></span></a>
<img width=100 height=100 						src="{{picture.pic.url}}" />
				</li>
			{% endfor %}
			</ul>
		{% else %}
			<p>عکسی وجود ندارد.</p>
		{% endif %}
</div>
</div>
{% endblock %}

RealEstate/RealEstate_admin/templates/RealEstate_admin/file/edit_file_menu_include.html
<ul class="nav nav-pills nav-stacked">
    <li class="{{ deal }}"><a href="../../editfile/{{ editable_file.pk }}/deal">معامله</a></li>
    <li class="{{ detail }}"  ><a href="../../editfile/{{ editable_file.pk }}/detail">مشخصات </a></li>
    <li class="{{ options }}"><a href="../../editfile/{{ editable_file.pk }}/options">امکانات </a></li>
    <li class="{{ images }}"><a href="../../editfile/{{ editable_file.pk }}/images">عکس ها </a></li>
</ul>

RealEstate/RealEstate_admin/templates/RealEstate_admin/file/edit_file_options.html
{% extends "Luna_admin/admin_master.html" %}
{% load staticfiles %}
{% block page_title %}{% block content_title %}{{ editable_file }}{% endblock %}{% endblock %}
{% block body_script %}
	<script  src="{% static 'Luna_admin/script/validate.js' %}"></script>
{% endblock %}
{% block content %}

<div class="row">
    <div class="col-sm-3">
     {% include "RealEstate_admin/file/edit_file_menu_include.html" %} 
    </div>
    <div class="col-sm-9">
            <form class="form-horizontal" role="form" action="{% url 'RealEstate_admin:editOptions' editable_file.pk %}" method="POST">
            {% csrf_token %}
<input type="hidden" value="{{option.id}}" name="option_id" />
		<input type="hidden" value="{{editable_file.pk}}" name="file_id" />

        <div class="row">
         <div class="col-md-6">
    <div class="form-group">
                <label for="sarmayesh" class="col-sm-4 control-label ">سرمایش</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" value="{{ option.sarmayesh|default_if_none:'' }}" id="sarmayesh" name="sarmayesh" placeholder="" >
                </div>
            </div>
         </div> 
         <div class="col-md-6">
                      <div class="form-group">
                <label for="garmayesh" class="col-sm-4 control-label ">گرمایش</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="garmayesh" name="garmayesh" value="{{ option.garmayesh }}" >
                </div>
            </div>
         </div>
     </div>

  <div class="row">
         <div class="col-md-6">
         <div class="form-group">
                <label for="kaf_saloon" class="col-sm-4  control-label">کف سالن</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="kaf_saloon" value="{{ option.kaf_saloon }}">
                </div>
            </div>

         </div> 
         <div class="col-md-6">
                  <div class="form-group">
                <label for="kaf_khabha" class="col-sm-4 control-label ">کف خواب ها</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="kaf_khabha" value="{{ option.kaf_khabha }}">
                </div>
            </div>
         </div>
     </div>

<div class="row">     
         <div class="col-md-6">
                  <div class="form-group">
                <label for="badane_divar" class="col-sm-4  control-label">بدنه / دیوار</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="badane_divar" value="{{ option.badane_divar }}">
                </div>
            </div>
         </div>

     </div>



          <div class="row" >
         <div class="form-group">
             <label for="inputEmail3" class="col-sm-2 control-label ">توضیحات</label>

                <div class="col-sm-10">
                 <textarea class="form-control fullWidth" rows="3" name="tozihat">{{ option.tozihat }}</textarea>

                </div>
            </div>

         </div> 


            <div class="row">
                
                <div class="col-sm-4">
                    
        <label class="checkbox ">
  <input type="checkbox" id="gaaz_va_fer_tookar" name="gaaz_va_fer_tookar" {% if option.gaaz_va_fer_tookar %} checked {% endif %}  > گاز و فر توکار
</label>
 <label class="checkbox ">
  <input type="checkbox" id="Open" name="Open" {% if option.Open %} checked {% endif %}> اوپن
</label>

<label class="checkbox ">
  <input type="checkbox" name="iphone" {% if option.iphone %} checked {% endif %}> آیفون
</label>



<label class="checkbox ">
  <input type="checkbox" name="parde" {% if option.parde %} checked {% endif %}> پرده
</label>
<label class="checkbox ">
  <input type="checkbox" name="komod" {% if option.komod %} checked {% endif %}> کمد
</label>
<label class="checkbox ">
  <input type="checkbox" name="looster" {% if option.looster %} checked {% endif %}> لوستر
</label>



<label class="checkbox ">
  <input type="checkbox" name="shoomine" {% if option.shoomine %} checked {% endif %}> شومینه
</label>
<label class="checkbox ">
  <input type="checkbox" name="master" {% if option.master %} checked {% endif %}> مستر
</label>
<label class="checkbox ">
  <input type="checkbox" name="kabin_doosh" {% if option.kabin_doosh %} checked {% endif %}> کابین دوش
</label>


<label class="checkbox ">
  <input type="checkbox" name="mahvare_markazi" {% if option.mahvare_markazi %} checked {% endif %}> ماهواره مرکزی
</label>
<label class="checkbox ">
  <input type="checkbox"name="internet_wireless" {% if option.internet_wireless %} checked {% endif %}> اینترنت وایرلس
</label>
                </div>            
                <div class="col-sm-4">
                    

<label class="checkbox ">
  <input type="checkbox" name="noorpardazi" {% if option.noorpardazi %} checked {% endif %}> نورپردازی
</label>
<label class="checkbox ">
  <input type="checkbox" name="noorgir_pasiyo" {% if option.noorgir_pasiyo %} checked {% endif %}> نورگیر / پاسیو
</label>
<label class="checkbox ">
  <input type="checkbox" name="tras" {% if option.tras %} checked {% endif %}> تراس
</label>



<label class="checkbox ">
  <input type="checkbox" name="anbari" {% if option.anbari %} checked {% endif %}> انباری
</label>
<label class="checkbox ">
  <input type="checkbox" name="parking" {% if option.parking %} checked {% endif %}> پارکینگ
</label>
<label class="checkbox ">
  <input type="checkbox" name="asansor" {% if option.asansor %} checked {% endif %}> آسانسور
</label>



<label class="checkbox ">
  <input type="checkbox" name="darb_automatik" {% if option.darb_automatik %} checked {% endif %}> درب اتوماتیک
</label>
<label class="checkbox ">
  <input type="checkbox" name="vorudi_zed_serghat" {% if option.vorudi_zed_serghat %} checked {% endif %}> ورودی ضد سرقت
</label>
<label class="checkbox ">
  <input type="checkbox" name="hayate_ekhtesasi" {% if option.hayate_ekhtesasi %} checked {% endif %}> حیات اختصاصی
</label>


<label class="checkbox ">
  <input type="checkbox" name="jarubarghi_markazi" {% if option.jarubarghi_markazi %} checked {% endif %}> جاروبرقی مرکزی
</label>



<label class="checkbox ">
  <input type="checkbox" name="shooting_zobale" {% if option.shooting_zobale %} checked {% endif %}> شوتینگ زباله
</label>
<label class="checkbox ">
  <input type="checkbox" name="kabinet" {% if option.kabinet %} checked {% endif %}> کابینت
</label>
                </div>            
                <div class="col-sm-4">
                <label class="checkbox ">
  <input type="checkbox" name="labi" {% if option.labi %} checked {% endif %}> لابی
</label>
<label class="checkbox ">
  <input type="checkbox" name="salon_ejtemaat" {% if option.salon_ejtemaat %} checked {% endif %}> سالن اجتماعات
</label>
<label class="checkbox ">
  <input type="checkbox" name="liting" {% if option.liting %} checked {% endif %}> لایتینگ
</label>



<label class="checkbox ">
  <input type="checkbox" name="estakhr" {% if option.estakhr %} checked {% endif %}> استخر
</label>
<label class="checkbox ">
  <input type="checkbox" name="sona" {% if option.sona %} checked {% endif %}> سونا
</label>
<label class="checkbox ">
  <input type="checkbox" name="jakuzi" {% if option.jakuzi %} checked {% endif %}> جکوزی
</label>



<label class="checkbox ">
  <input type="checkbox" name="salon_varzesh" {% if option.salon_varzesh %} checked {% endif %}> سالن ورزش
</label>
<label class="checkbox ">
  <input type="checkbox" name="roof_garden" {% if option.roof_garden %} checked {% endif %}> روف گاردن
</label>
<label class="checkbox ">
  <input type="checkbox" name="barbecu" {% if option.barbecu %} checked {% endif %}> باربیکیو
</label>
    



<label class="checkbox ">
  <input type="checkbox" name="elam_harigh" {% if option.elam_harigh %} checked {% endif %}> اعلام حریق
</label>
<label class="checkbox ">
  <input type="checkbox" name="etfa_harigh" {% if option.etfa_harigh %} checked {% endif %}> اطفا حریق
</label>



<label class="checkbox ">
  <input type="checkbox" name="ab_taht_feshar" {% if option.ab_taht_feshar %} checked {% endif %}> آب تحت فشار
</label>

                </div>            

            </div>


            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">ثبت تغییرات</button>
                </div>
            </div>
        </form>

    </div>
</div>
{% endblock %}

RealEstate/RealEstate_admin/templates/RealEstate_admin/file/matched_files_requests.html
{% extends "Luna_admin/admin_master.html" %}
{% load staticfiles %}
{% load luna_filters %}

{% block page_title %}{% block content_title %}درخواستهای مطابق با فایلها{% endblock %}{% endblock %}
{% block body_script %}
	<script  src="{% static 'RealEstate_admin/script/file/matched_files_requests.js' %}"></script>
{% endblock %}
{% block content %}
<div class="thumbnail">
	{% if not matched_dict %}
		<p class="notFind"><span class="glyphicon glyphicon-minus"></span>موردی وجود ندارد.</p>
	{% else %}
        <table class="table table-responsive table-striped table-hover toptable">
            <thead>
                <tr><td>فایلهای مطابق</td><td>نام درخواست کننده</td><td>نام خانوادگی درخواست کننده</td><td>شماره تماس</td> <td>تاریخ ثبت</td><td>مشاهده درخواست</td></tr>
            </thead>
            <tbody>
			{% for key, value_list  in  matched_dict.items %}
			<tr>
				<td class="showHide">+</td><td>{{key.name}}</td><td>{{key.family}}</td><td>	{{key.phone_no}}</td><td>{{key.creation_date| persian_date}}</td> <td> <a href="../add_edit_request/{{ key.id }}/"><span class="glyphicon glyphicon-floppy-saved"></span></a></td>
			</tr>		 






				
				<tr class="nested">
<td >
					<table  id="deals" class="table table-bordered table-condensed table-responsive table-striped table-hover">
					 <thead>
                				<tr><td>نوع معامله</td><td>نوع ملک</td><td>مشاهده فایل</td></tr>
            				</thead>
					<tbody>
				{% for value in value_list %}
					<tr><td>{{value|format_deal_type}}</td><td>{{value.deal_file.property_detail|format_property_type}}</td><td> <a href="../editfile/{{ value.id }}/deal"><span class="glyphicon glyphicon-floppy-saved"></span></a></td></tr>
				{% endfor %}
					
					</tbody>
        </table>
	</tr>			

</td>


			{% endfor %}
            </tbody>
        </table>
{% endif %}
</div>
{% endblock %}