RealEstate/Luna_admin/urls.py
from django.conf.urls import patterns, url
from Luna_admin import views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
        url(r'^login/$', views.login, name='login'),
	 url(r'^signout/$', views.signout, name='signout'),
        url(r'^change_password/$', login_required(views.change_password), name='change_password'),
	url(r'^sendsms/$', login_required(views.send_sms), name='sendSms'),
	url(r'^sendsms/(?P<cell_no>.+)/(?P<draft_id>\d+)$', login_required(views.send_sms), name='sendSms'),
	url(r'^user_list/$', login_required(views.user_list), name='user_list'),
	url(r'^change_user_active_status/(?P<user_id>\d+)/$', login_required(views.change_user_active_status), 				name='change_user_active_status'),
	url(r'^add_edit_user/((?P<user_id>\d+)/)?$',login_required(views.add_edit_user),name='add_edit_user'),
)

RealEstate/RealEstate/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from RealEstate import view

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',

	url(r'^admin/', include('Luna_admin.urls',namespace='Luna_admin')),
	url(r'^realestate/admin/',include('RealEstate_admin.urls',namespace='RealEstate_admin')),
	url(r'^$',view.home,name='home'),
	url(r'^search$',view.search,name='search'),
	url(r'^detail/(?P<file_id>\d+)/$',view.property_detail,name='detail'),
	url(r'^contact_us$',view.contact_us,name='contact_us'),
	url(r'^about_us$',view.about_us,name='about_us'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

RealEstate/RealEstate/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from RealEstate_admin.models import File, Deal, PropertyRequest, PropertyDetail, PropertyOption


class UserStatistics(models.Model):
    total_count = models.IntegerField()
    daily_count = models.IntegerField()
    today = models.DateTimeField(auto_now_add=True)


@receiver(pre_save)
def set_is_dirty_when_updating(sender, instance, **kwargs):
    '''
    when updating File, Deal, PropertyDetail, PropertyOption, and PropertyRequest, set isdirty=true
    '''
    if sender in [File, Deal, PropertyDetail, PropertyOption, PropertyRequest]:
        #if it is update(not create).
        if instance.id:
            instance.is_dirty = True

RealEstate/RealEstate_admin/models.py
#! /usr/bin/env python
# -*- coding: utf8 -*-

"""
@author: AR.Jozaghi
@organization: LunaSoft
@copyright: Copyright © 2014 LUNA
@license:
@contact:
"""
from django.db import models
from django_resized import ResizedImageField

#-----------------------------------------------------------------------

# PropertyOption Model
class PropertyOption(models.Model):
    sarmayesh = models.CharField(max_length=500, blank=True, null=True, verbose_name="سرمایش")
    garmayesh = models.CharField(max_length=500, blank=True, null=True, verbose_name="گرمایش")
    kaf_saloon = models.CharField(max_length=500, blank=True, null=True, verbose_name="کف سالن")
    kaf_khabha = models.CharField(max_length=500, blank=True, null=True, verbose_name="کف خوابها")
    badane_divar = models.CharField(max_length=500, blank=True, null=True, verbose_name="بدنه/دیوار")
    tozihat = models.CharField(max_length=1000, blank=True, null=True, verbose_name="توضیحات")
    mahvare_markazi = models.BooleanField(verbose_name="ماهواره مرکزی")
    internet_wireless = models.BooleanField(verbose_name="اینترنت وایرلس")
    jarubarghi_markazi = models.BooleanField(verbose_name="جاروبرقی مرکزی")
    shooting_zobale = models.BooleanField(verbose_name="شوتینگ زباله")
    salon_ejtemaat = models.BooleanField(verbose_name="سالن اجتماعات")
    liting = models.BooleanField(verbose_name="لایتینگ")
    estakhr = models.BooleanField(verbose_name="استخر")
    sona = models.BooleanField(verbose_name="سونا")
    jakuzi = models.BooleanField(verbose_name="جکوزی")
    salon_varzesh = models.BooleanField(verbose_name="سالن ورزش")
    roof_garden = models.BooleanField(verbose_name="روف گاردن")
    barbecu = models.BooleanField(verbose_name="باربکیو")
    elam_harigh = models.BooleanField(verbose_name="اعلام حریق")
    etfa_harigh = models.BooleanField(verbose_name="اطفاء حریق")
    ab_taht_feshar = models.BooleanField(verbose_name="آب تحت فشار")
    kabinet = models.BooleanField(verbose_name="کابینت")
    gaaz_va_fer_tookar = models.BooleanField(verbose_name="گاز و فر توکار")
    Open = models.BooleanField(verbose_name="اوپن")
    iphone = models.BooleanField(verbose_name="آیفون")
    parde = models.BooleanField(verbose_name="پرده")
    komod = models.BooleanField(verbose_name="کمد")
    looster = models.BooleanField(verbose_name="لوستر")
    shoomine = models.BooleanField(verbose_name="شومینه")
    master = models.BooleanField(verbose_name="مستر")
    kabin_doosh = models.BooleanField(verbose_name="کابین دوش")
    noorpardazi = models.BooleanField(verbose_name="نورپردازی")
    noorgir_pasiyo = models.BooleanField(verbose_name="نورگیر/پاسیو")
    tras = models.BooleanField(verbose_name="تراس")
    anbari = models.BooleanField(verbose_name="انباری")
    parking = models.BooleanField(verbose_name="پارکینگ")
    asansor = models.BooleanField(verbose_name="آسانسور")
    darb_automatik = models.BooleanField(verbose_name="درب اتوماتیک")
    vorudi_zed_serghat = models.BooleanField(verbose_name="ورودی ضد سرقت")
    hayate_ekhtesasi = models.BooleanField(verbose_name="حیات اختصاصی")
    labi = models.BooleanField(verbose_name="لابی")

    is_dirty = models.BooleanField(default=False)
    modified_date = models.DateTimeField(auto_now=True)

    desktop_id = models.IntegerField(null=True)
#-----------------------------------------------------------------------

# PropertyDetail Model
class PropertyDetail(models.Model):
    #property type
    PROPERTY_TYPE = (
        ('apartment', 'آپارتمان ‍‍‍‍‍‍‍'),
        ('house', 'خانه'),
        ('suite', 'سوئیت'),
        ('shop', 'مغازه'),
        ('other', 'سایر')
    )
    property_type = models.CharField(max_length=20, choices=PROPERTY_TYPE, verbose_name="نوع ملک")
    other_property_type_name = models.CharField(max_length=200, blank=True, null=True, verbose_name="نوع ملک")
    #usage type
    USAGE_TYPE = (
        ('maskuny', 'سند مسکونی'),
        ('maskuny_tejari', 'مسکونی تجاری'),
        ('other', 'سایر')
    )
    usage_type = models.CharField(max_length=20, choices=USAGE_TYPE, verbose_name="نوع کاربری")
    other_usage_type_name = models.CharField(max_length=200, blank=True, null=True, verbose_name="نوع کاربری")
    no_bedrooms = models.IntegerField(null=True, verbose_name="تعداد خواب")
    no_floor = models.CharField(max_length=50, null=True, blank=True, verbose_name="تعداد طبقات")
    floors = models.CharField(max_length=50, null=True, blank=True, verbose_name="طبقه")
    tedade_vahed = models.CharField(max_length=50, null=True, blank=True, verbose_name="تعداد واحد")
    area = models.CharField(max_length=500, blank=True, null=True, verbose_name="محدوده")
    address = models.CharField(max_length=200, blank=True, null=True, verbose_name="آدرس")
    masahat_zamin = models.BigIntegerField(null=True, verbose_name="مساحت زمین")
    masahat_kol = models.BigIntegerField(null=True, verbose_name="مساحت کل")
    zirbana = models.BigIntegerField(null=True, verbose_name="زیربنا")
    ToolBar = models.BigIntegerField(null=True, verbose_name="طول بر")
    zabete_sakht = models.CharField(max_length=100, blank=True, null=True, verbose_name="ضابطه ساخت")
    sene_bana = models.IntegerField(null=True, verbose_name="سن بنا")
    mogheiyat = models.CharField(max_length=100, blank=True, null=True, verbose_name="موقعیت")
    noe_sanad = models.CharField(max_length=500, blank=True, null=True, verbose_name="نوع سند")
    vame_banki = models.CharField(max_length=500, blank=True, null=True, verbose_name="وام بانکی")
    noe_saghf = models.CharField(max_length=500, blank=True, null=True, verbose_name="نوع سقف")
    nama = models.CharField(max_length=500, blank=True, null=True, verbose_name="نما")
    view_ya_manzare = models.CharField(max_length=500, blank=True, null=True, verbose_name="ویو/منظره")

    is_dirty = models.BooleanField(default=False)
    modified_date = models.DateTimeField(auto_now=True)

    desktop_id = models.IntegerField(null=True)
#-----------------------------------------------------------------------
#File Model
class File(models.Model):
    code = models.IntegerField(default=0, blank=True)
    code_type = models.CharField(max_length=1, default='w')  # W for Website, D for Desktop, and M for Mobile
    creation_date = models.DateTimeField(auto_now_add=True)

    @property
    def file_code(self):
        return str(self.code) + self.code_type
    #owner data
    owner_name = models.CharField(max_length=200, blank=True, null=True)
    owner_family = models.CharField(max_length=200, blank=True)
    owner_tell = models.CharField(max_length=20)
    owner_cell = models.CharField(max_length=20)

    property_detail = models.OneToOneField(PropertyDetail, blank=True, null=True)
    property_option = models.OneToOneField(PropertyOption, blank=True, null=True)

    is_dirty = models.BooleanField(default=False)
    modified_date = models.DateTimeField(auto_now=True)

    desktop_id = models.IntegerField(null=True)

    def __unicode__(self):
        return u'کد فایل : {0} | نام و نام خانوادگی مالک : {1} {2} | شماره همراه مالک : {3}'.format(self.file_code,
                                                                                                       self.owner_name,
                                                                                                       self.owner_family,
                                                                                                       self.owner_cell)


#-----------------------------------------------------------------------
# Deal Model
class Deal(models.Model):
    DEAL_TYPE = (
        ('rahn_va_ejare', u'رهن و اجاره'),
        ('rahn_kamel', u'رهن کامل'),
        ('forush_malekiyat', u'فروش مالکیت'),
        ('forush_sarghofly', u'فروش سرقفلی'),
        ('moaveze', u'معاوضه'),
        ('pish_forush', u'پیش فروش'),
        ('mosharekat_dar_sakht', u'مشارکت در ساخت')
    )
    deal_type = models.CharField(max_length=20, choices=DEAL_TYPE)
    BAZDID_TYPE = (
        ('takhliye', u'تخلیه'),
        ('negahban', u'نگهبان'),
        ('sokunat_malek', u'سکونت مالک '),
        ('sokunat_mostajer', u'سکونت مستاجر'),
        ('klid_bongah', u'کلید بنگاه')
    )
    bazdid_type = models.CharField(max_length=20, choices=BAZDID_TYPE)
    name_mostajer_ya_negahban = models.CharField(max_length=200, blank=True, null=True)
    tell_mostajer_ya_negahban = models.CharField(max_length=20, blank=True, null=True)
    tarikhe_takhliye = models.DateTimeField(null=True)
    total_price = models.BigIntegerField(null=True)
    meter_price = models.BigIntegerField(null=True)
    rahne_kamel_price = models.BigIntegerField(null=True)
    rahn_price = models.BigIntegerField(null=True)
    ejare_price = models.BigIntegerField(null=True)
    charge_price = models.BigIntegerField(null=True)
    ghabel_tabdil = models.CharField(max_length=200, blank=True, null=True)
    is_active = models.BooleanField()
    is_special = models.BooleanField(default=False)
    deal_file = models.ForeignKey(File)

    deal_creation_date = models.DateTimeField(auto_now_add=True)
    deal_end_date = models.DateTimeField(null=True)
    deal_name = models.CharField(max_length=100, blank=True, null=True)
    deal_family = models.CharField(max_length=100, blank=True, null=True)
    deal_cell = models.CharField(max_length=100, blank=True, null=True)
    deal_description = models.CharField(max_length=300, blank=True, null=True)
    is_synced = models.BooleanField(default=True)

    is_dirty = models.BooleanField(default=False)
    modified_date = models.DateTimeField(auto_now=True)

    desktop_id = models.IntegerField(null=True)

#-----------------------------------------------------------------------

# Pic Model
class Picture(models.Model):
    pic = ResizedImageField(max_width=700, max_height=500, upload_to='documents')
    pic_file = models.ForeignKey(File)
    caption = models.CharField(max_length=100, blank=True, null=True)

#-----------------------------------------------------------------------

RealEstate/RealEstate/templates/about_us.html
{% extends 'master.html' %}
{% block page_title %}درباره ما{% endblock %}

{% block content %}
<p class='title'><span class='glyphicon glyphicon-briefcase'></span> {{ profile.about_us_title }}</p>
<div class='container'>
{{ profile.about_us |linebreaks }}
</div>
{% endblock %}

RealEstate/RealEstate/templates/contact_us.html
{% extends 'master.html' %}
{% load staticfiles %}
{% block page_title %}درخواست مشاوره{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'style/contact_us/index.css' %}" />
{% endblock %}
{% block body_script %}
	<script  src="{% static 'Luna_admin/script/validate.js' %}"></script>
	<script src="{% static 'script/contact_us.js' %}"></script>
{% endblock %}
{% block content %}
<div id="wrapper"  style="margin:0 auto;">
 <div class="title"><span class="icon glyphicon glyphicon-log-in"></span>درخواست مشاوره</div>
<div id="contactUsFormErrors"></div>
{% if messages %}
           {% for message in messages %}
           
              <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% ifequal message.tags 'error' %}
              	<span class='glyphicon glyphicon-remove'></span>
              {% else %}
              	<span class='glyphicon glyphicon-ok'></span>
              {% endifequal %}
              	{{ message }}
              </div>
           {% endfor %}
{% endif %}


<form class="form-horizontal" id="contactUsForm" name="contactUsForm" role="form" method="POST" action="{% url 'contact_us' %}">
   {% csrf_token %}

    <div class="control-group">
                <label for="name" class="control-label">نام</label>
                <div class="controls">
                    <input type="text" class="form-control" id="name" name="name" />
                </div>
    </div>

	<div class="control-group">
                <label for="phone_no" class="control-label">شماره تماس</label>
                <div class="controls">
                    <input type="text" class="form-control" id="phone_no" name="phone_no" />                  
                </div>
    </div>	

   <div class="control-group">
                <label for="title" class="control-label">موضوع</label>
                <div class="controls">
                    <input type="text" class="form-control" id="title" name="title" />                   
                </div>
    </div>
 
   
            <div class="control-group">
                <label for="main_text" class="control-label">متن<span class="required">*</span></label>
                <div class="controls">
                    <textarea class="form-control" name="main_text" id="main_text" ></textarea>
                </div>
        </div>

  
    <div class="control-group">
<div class="controls">
        <button id="sendSmsBtn" type="submit" class="btn btn-primary">ارسال</button>
   </div>
</div>
</form>
</div>
{% endblock %}

RealEstate/RealEstate/templates/detail.html
{% extends 'master.html' %}
{% load staticfiles %}
{% load luna_filters %}
{% block page_title %}مشاهده جزییات{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'style/slider/themes/default/default.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'style/slider/nivo-slider.css' %}" type="text/css" media="screen" />
	<link rel="stylesheet" href="{% static 'style/detail/index.css' %}" />
{% endblock %}
{% block head_script %}
<script type="text/javascript" src="{% static 'script/jquery-1.10.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'style/slider/jquery.nivo.slider.js' %}"></script>
    <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider({controlNavThumbs: true, effect: 'fade', pauseTime: 5000});
    });
    </script>
{% endblock %}
{% block body_script %}
<!--<script type="text/javascript" src="{% static 'script/detail/detail.js' %}"></script>-->
{% endblock %}
{% block content %}
		
		{% if file.picture_set.count %}
		
		
		
<div class="row">
<div class="col-md-7" >

   <div class='container marginT'>
        <div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider">
                {% for picture in file.picture_set.all %}
                <img src="{{picture.pic.url}}" data-thumb="{{picture.pic.url}}" 
                title="<div style=text-align:center;font-size:15px;>{{picture.caption}} </div>" />   
                {% endfor %}    
            </div>
        </div>
    </div>

</div>
			<!--<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">		
				<div class="carousel-inner">
					{% for picture in file.picture_set.all %}
   						{% if forloop.counter == 1 %}					
			 				<div class="item active">				
						{% else %}
							<div class="item">
						{% endif %}
                           	 		<img src="{{picture.pic.url}}">
                        	 		</div>
			 		{% endfor %}
			</div>
			
                    		<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                       		<span class="glyphicon glyphicon-chevron-left"></span>
                    		</a>
                    		<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                        	<span class="glyphicon glyphicon-chevron-right"></span>
                    		</a>
	 
			
        </div>-->

		{% endif %}

<div class="col-md-5">
<!-- deal -->
<div style="background-color:white;margin:5px;padding:5px;border-radius:4px;">
 	<div >
                 
                     <p class="title"> <span class="glyphicon glyphicon-briefcase"></span>
                       معامله
                     </p>
         </div>   

	  <div class="row">
		<div class="col-xs-3 col-sm-2 col-md-3">
		 کد
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			
			{{ file.file_code }}
						
		</div>

		<div class="col-xs-3 col-sm-2 col-md-3">
		 نوع معامله
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			
			{{ active_deal | format_deal_type  }}
						
		</div>
</div>
		

<div class="row">		
	
{% if active_deal.rahne_kamel_price %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 رهن کامل
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			
			{{ active_deal.rahne_kamel_price | money_format }}
						
		</div>
	{% endif %}
	
	{% if active_deal.meter_price %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		قیمت هر متر
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{active_deal.meter_price | money_format}}
		</div>
	{% endif %}
	</div>

		
	 
<div class="row">
	{% if active_deal.total_price %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		قیمت کل
		</div>
		<div class="col-xs-3 col-sm-2 col-md-4 property-value">
			{{active_deal.total_price | money_format}}
		</div>
	{% endif %}
</div>

<div class="row">
{% if active_deal.rahn_price %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 رهن
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			
			{{ active_deal.rahn_price  | money_format}}
						
		</div>
	 	{% endif %}

		{% if active_deal.ejare_price %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		اجاره
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{active_deal.ejare_price | money_format}}
		</div>
		{% endif %}
</div>
	
	

	<div class="row">

	{% if active_deal.tarikhe_takhliye %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 تاریخ تخلیه
		</div>
	
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			
			{{ active_deal.tarikhe_takhliye | persian_date }}
						
		</div>
	{% endif %}

	{% if active_deal.charge_price %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		مبلغ شارژ
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{active_deal.charge_price | money_format}}
		</div>
	{% endif %}

	{% if active_deal.ghabel_tabdil %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		قابل تبدیل
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			
			{{ active_deal.ghabel_tabdil }}
						
		</div>
	{% endif %}
	</div>

<!-- property details -->

 	<div >
                 
                     <p class="title"> <span class="glyphicon glyphicon-file"></span>
                       مشخصات
                     </p>
         </div>   


        <div class="row">
		<div class="col-xs-3 col-sm-2 col-md-3">
		 نوع ملک
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			
			{{ file.property_detail | format_property_type }}
						
		</div>
		
	{% if file.property_detail.usage_type %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 نوع کاربری
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			
			{{ file.property_detail | format_usage_type }}
						
		</div>	
{% endif %}
</div>
<div class="row">
		{% if file.property_detail.no_floor %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 تعداد طبقات
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.no_floor}}
		</div>
	{% endif %}


{% if file.property_detail.floors %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 طبقه
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.floors}}
		</div>
	{% endif %}
</div>
<div class="row">
	{% if file.property_detail.no_bedrooms %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 تعداد خواب
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.no_bedrooms}}
		</div>
	{% endif %}



{% if file.property_detail.tedade_vahed %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		تعداد واحد
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.tedade_vahed}}
		</div>
	{% endif %}	
	
</div>


	<div class="row">
{% if file.property_detail.nama %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		نما
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.nama}}
		</div>
		{% endif %}

		{% if file.property_detail.view_ya_manzare %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		ویو/منظره
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.view_ya_manzare}}
		</div>
	{% endif %}
</div>
<div class="row">
	{% if file.property_detail.area %}
		<div class="col-xs-3 col-md-3 col-sm-2">
		 محدوده
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.area}}
		</div>
	{% endif %}
	
{% if file.property_detail.masahat_zamin %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 مساحت زمین
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.masahat_zamin}}
		</div>
	{% endif %}
</div>

<div class="row">
{% if file.property_detail.masahat_kol %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		مساحت کل
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.masahat_kol}}
		</div>
	{% endif %}

{% if file.property_detail.zirbana %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 زیربنا
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.zirbana}}
		</div>
	{% endif %}
	</div>
	<div class="row">
	

{% if file.property_detail.ToolBar %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 طول بر
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.ToolBar}}
		</div>
	{% endif %}

{% if file.property_detail.zabete_sakht %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 ضابطه ساخت
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.zabete_sakht}}
		</div>
	{% endif %}
</div>
<div class="row">
{% if file.property_detail.sene_bana %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		سن بنا
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.sene_bana}}
		</div>
	{% endif %}
	
	
{% if file.property_detail.mogheiyat %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 موقعیت
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.mogheiyat}}
		</div>
	{% endif %}
</div>

<div class="row">
{% if file.property_detail.noe_sanad %}
		<div class="col-xs-3 col-md-3 col-sm-2">
		 نوع سند
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.noe_sanad}}
		</div>
	{% endif %}

{% if file.property_detail.vame_banki %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		 وام بانکی
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.vame_banki}}
		</div>
	{% endif %}

	</div>
<div class="row">
{% if file.property_detail.noe_saghf %}
		<div class="col-xs-3 col-sm-2 col-md-3">
		نوع سقف
		</div>
		<div class="col-xs-3 col-sm-2 col-md-3 property-value">
			{{file.property_detail.noe_saghf}}
		</div>
	{% endif %}
</div>



<!-- property options -->
{% if file.property_option %}
 	<div class="row" style="margin-right:3px;">           
                 
                     <p class="title"> <span class="glyphicon glyphicon-plus"></span>
                        امکانات
                     </p>
         </div> 

	<div>{% format_fields file.property_option 0 %}</div>
	<div style="margin-bottom:20px;">{% format_fields file.property_option 1 %}</div>
	
{% endif %}
</div><!--end col-md-6 -->
</div>
</div>
</div>
{% endblock %}