RealEstate/Luna_admin/urls.py
from django.conf.urls import patterns, url
from Luna_admin import views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
        url(r'^login/$', views.login, name='login'),
	 url(r'^signout/$', views.signout, name='signout'),
        url(r'^change_password/$', login_required(views.change_password), name='change_password'),
	url(r'^sendsms/$', login_required(views.send_sms), name='sendSms'),
	url(r'^sendsms/(?P<cell_no>.+)/(?P<draft_id>\d+)$', login_required(views.send_sms), name='sendSms'),
	url(r'^user_list/$', login_required(views.user_list), name='user_list'),
	url(r'^change_user_active_status/(?P<user_id>\d+)/$', login_required(views.change_user_active_status), 				name='change_user_active_status'),
	url(r'^add_edit_user/((?P<user_id>\d+)/)?$',login_required(views.add_edit_user),name='add_edit_user'),
)

RealEstate/RealEstate/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from RealEstate import view

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',

	url(r'^admin/', include('Luna_admin.urls',namespace='Luna_admin')),
	url(r'^realestate/admin/',include('RealEstate_admin.urls',namespace='RealEstate_admin')),
	url(r'^$',view.home,name='home'),
	url(r'^search$',view.search,name='search'),
	url(r'^detail/(?P<file_id>\d+)/$',view.property_detail,name='detail'),
	url(r'^contact_us$',view.contact_us,name='contact_us'),
	url(r'^about_us$',view.about_us,name='about_us'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

RealEstate/RealEstate_admin/urls.py
from django.conf.urls import patterns, url
from RealEstate_admin import files, home, end_deals, special_files
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
                       #admin home page
                       url(r'^$', login_required(home.index), name='home'),
                       # show ending deals
                       url(r'^enddeals/$', login_required(end_deals.get_deals), name="endDeals"),
                       #add new file
                       url(r'^files$', login_required(files.index), name='fileIndex'),
                       url(r'^addnewfile$', login_required(files.add_new_file), name='addNewFile'),
                       #edit file
                       url(r'^editfile/(?P<file_id>\d+)/deal', login_required(files.edit_file_deal),
                           name='editFileDeal'),
                       url(r'^editfile/editdeal$', login_required(files.edit_deal), name='editDeal'),
                       url(r'^editfile/(?P<file_id>\d+)/detail', login_required(files.edit_file_detail),
                           name='editFileDetail'),
                       url(r'^enddeal/$', login_required(files.end_deal), name='endDeal'),
                       url(r'^addnewDeal/$', login_required(files.add_new_deal), name='addNewDeal'),
                       url(r'^editfile/editownerdetail$', login_required(files.edit_detail_owner),
                           name='editOwnerDetail'),
                       url(r'^editfile/editpropertydetail$', login_required(files.edit_detail_property_detail),
                           name='editPropertyDetail'),
                       url(r'^editfile/editotherpropertydetail$', login_required(files.edit_detail_other_detail),
                           name='editOtherPropertyDetail'),
                       url(r'^editfile/(?P<file_id>\d+)/options', login_required(files.edit_file_options),
                           name='editFileOptions'),
                       url(r'^editfile/(?P<file_id>\d+)/editoptions$', login_required(files.edit_options),
                           name='editOptions'),
                       url(r'^editfile/(?P<file_id>\d+)/images', login_required(files.edit_file_images),
                           name='editFileImages'),
                       url(r'^delete_image/(?P<file_id>\d+)/(?P<image_id>\d+)/$', login_required(files.delete_image),
                           name='delete_image'),
                       url(r'^editfile/(?P<file_id>\d+)/options', login_required(files.edit_file_options),
                           name='editFileOptions'),
                       url(r'^matched_files_requests/$', login_required(files.matched_files_requests),
                           name='matchedFilesRequests'),
                       #property request
                       url(r'^property_requests$', login_required(files.property_request_index),
                           name='propertyRequests'),
                       url(r'^add_edit_request/((?P<property_request_id>\d+)/)?$',
                           login_required(files.add_edit_property_request), name='addEditPropertyRequest'),
                       url(r'^delete_property_request/(?P<property_request_id>\d+)/$',
                           login_required(files.delete_property_request), name='deletePropertyRequest'),
                       url(r'^contact_us$', login_required(files.list_contact_us), name='contactUs'),
                       url(r'^delete_contact/(?P<contact_id>\d+)/$', login_required(files.delete_contact),
                           name='deleteContact'),
                       #special deals
                       url(r'^special_deals/$', login_required(special_files.special_files), name='special'),
                       url(r'^delete_special/(?P<file_id>\d+)/$', login_required(special_files.delete),
                           name='delete_special'),

                       #profile
                       url(r'^profile/$', login_required(files.add_edit_profile),
                           name='add_edit_profile'),
                       )

RealEstate/RealEstate_admin/forms.py
#! /usr/bin/env python
# -*- coding: utf8 -*-
"""
@author: AR.Jozaghi
@organization: LunaSoft
@copyright: Copyright © 2014 LUNA
@license:
@contact:
"""
from django import forms
from django.forms import ModelForm
from RealEstate_admin import models


class AddNewFileForm(forms.Form):
    owner_name = forms.CharField(max_length=100, required=False)
    owner_family = forms.CharField(max_length=100)
    owner_cell = forms.CharField(max_length=11)
    area = forms.CharField(max_length=100)
    property_type = forms.CharField(max_length=20)
    other_property_type_name = forms.CharField(max_length=100, required=False)
    deal_type = forms.CharField(max_length=20)
    masahat_kol = forms.IntegerField(required=False)
    total_price = forms.IntegerField(required=False)
    rahne_kamel_price = forms.IntegerField(required=False)
    rahn_price = forms.IntegerField(required=False)
    ejare_price = forms.IntegerField(required=False)
    address = forms.CharField(max_length=200)
    is_synced = forms.BooleanField(required=False)


class EditDealForm(forms.Form):
    deal_type = forms.CharField(max_length=20)
    bazdid_type = forms.CharField(max_length=20)
    name_mostajer_ya_negahban = forms.CharField(max_length=200, required=False)
    tell_mostajer_ya_negahban = forms.CharField(max_length=20, required=False)
    tarikhe_takhliye = forms.CharField(max_length=12, required=False)
    total_price = forms.IntegerField(required=False)
    meter_price = forms.IntegerField(required=False)
    rahne_kamel_price = forms.IntegerField(required=False)
    rahn_price = forms.IntegerField(required=False)
    ejare_price = forms.IntegerField(required=False)
    ghabel_tabdil = forms.CharField(max_length=100, required=False)
    charge_price = forms.IntegerField(required=False)
    deal_id = forms.IntegerField()
    file_id = forms.IntegerField()
    is_synced = forms.BooleanField(required=False)


class EditOwnerDetailForm(forms.Form):
    owner_name = forms.CharField(max_length=100)
    owner_family = forms.CharField(max_length=100)
    owner_tell = forms.CharField(max_length=11, required=False)
    owner_cell = forms.CharField(max_length=20)
    file_id = forms.IntegerField()


class EditPropertyDetailForm(forms.Form):
    property_type = forms.CharField(max_length=20)
    other_property_type_name = forms.CharField(max_length=200, required=False)
    usage_type = forms.CharField(max_length=20)
    other_usage_type_name = forms.CharField(max_length=200, required=False)
    address = forms.CharField(max_length=200, required=False)
    area = forms.CharField(max_length=100)
    no_bedrooms = forms.IntegerField(required=False)
    no_floor = forms.CharField(max_length=50, required=False)
    floors = forms.CharField(max_length=50, required=False)
    tedade_vahed = forms.CharField(max_length=50, required=False)
    masahat_zamin = forms.IntegerField(required=False)
    masahat_kol = forms.IntegerField()
    zirbana = forms.IntegerField(required=False)
    ToolBar = forms.IntegerField(required=False)
    file_id = forms.IntegerField()
    property_detail_id = forms.IntegerField()


class EditOtherPropertyDetailForm(forms.Form):
    file_id = forms.IntegerField()
    property_detail_id = forms.IntegerField()
    zabete_sakht = forms.CharField(max_length=100, required=False)
    sene_bana = forms.IntegerField(required=False)
    mogheiyat = forms.CharField(max_length=100, required=False)
    noe_sanad = forms.CharField(max_length=100, required=False)
    noe_saghf = forms.CharField(max_length=100, required=False)
    vame_banki = forms.CharField(max_length=100, required=False)
    nama = forms.CharField(max_length=100, required=False)
    view_ya_manzare = forms.CharField(max_length=100, required=False)


class EditPropertyOptionForm(forms.Form):
    sarmayesh = forms.CharField(max_length=500, required=False)
    garmayesh = forms.CharField(max_length=500, required=False)
    kaf_saloon = forms.CharField(max_length=500, required=False)
    kaf_khabha = forms.CharField(max_length=500, required=False)
    badane_divar = forms.CharField(max_length=500, required=False)

    tozihat = forms.CharField(max_length=1000, required=False)
    mahvare_markazi = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    internet_wireless = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    jarubarghi_markazi = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    shooting_zobale = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    salon_ejtemaat = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    liting = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    estakhr = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    sona = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    jakuzi = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    salon_varzesh = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    roof_garden = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    barbecu = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    elam_harigh = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    etfa_harigh = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    ab_taht_feshar = forms.BooleanField(required=False, widget=forms.CheckboxInput())

    kabinet = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    gaaz_va_fer_tookar = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    Open = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    iphone = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    parde = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    komod = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    looster = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    shoomine = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    master = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    kabin_doosh = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    noorpardazi = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    noorgir_pasiyo = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    tras = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    anbari = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    parking = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    asansor = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    darb_automatik = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    vorudi_zed_serghat = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    hayate_ekhtesasi = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    labi = forms.BooleanField(required=False, widget=forms.CheckboxInput())


class PictureForm(forms.Form):
    pic = forms.FileField(label='انتخاب فایل :')
    caption = forms.CharField(max_length=100, required=False)

class PropertyRequestForm(forms.Form):
    property_request_id = forms.IntegerField(required=False)
    name = forms.CharField(max_length=100, required=False)
    family = forms.CharField(max_length=100, required=False)
    phone_no = forms.CharField(max_length=20, required=False)
    total_price = forms.IntegerField(required=False)
    rahne_kamel_price = forms.IntegerField(required=False)
    rahn_price = forms.IntegerField(required=False)
    ejare_price = forms.IntegerField(required=False)
    property_type = forms.CharField(max_length=20)
    other_property_type_name = forms.CharField(max_length=200, required=False)
    deal_type = forms.CharField(max_length=20)
    area = forms.CharField(max_length=100, required=False)
    description = forms.CharField(max_length=1000, required=False)

class EndDealForm(forms.Form):
    end_deal_date = forms.CharField(max_length=100, required=False)
    deal_name = forms.CharField(max_length=100, required=False)
    deal_family = forms.CharField(max_length=100, required=False)
    deal_cell = forms.CharField(max_length=100, required=False)
    deal_description = forms.CharField(max_length=300, required=False)
    file_id = forms.IntegerField()
    deal_id = forms.IntegerField()


class AddNewDealForm(forms.Form):
    file_id = forms.IntegerField()


class ContactUsForm(forms.Form):
    title = forms.CharField(max_length=100, required=False)
    name = forms.CharField(max_length=100, required=False)
    main_text = forms.CharField(max_length=1000)
    phone_no = forms.CharField(max_length=20, required=False)


class AddSpecialDealForm(forms.Form):
    file_code = forms.CharField()


class AddNewProfileForm(ModelForm):
    class Meta:
        model = models.Profile

RealEstate/RealEstate_admin/views.py
from django.shortcuts import render

# Create your views here.

RealEstate/RealEstate_admin/templates/RealEstate_admin/request/add_edit_request.html
{% extends "Luna_admin/admin_master.html" %}
{% load staticfiles %}
{% load luna_filters %}
{% block page_title %}{% block content_title %}ایجاد درخواست ملک{% endblock %}{% endblock %}
{% block body_script %}
	<script  src="{% static 'Luna_admin/script/validate.js' %}"></script>
	<script  src="{% static 'RealEstate_admin/script/request/add_edit_request.js' %}"></script>
{% endblock %}

{% block content %}
<div id="addEditPropertyRequestFormError"></div>
<form class="form-horizontal" id="addEditPropertyRequestForm" name="addEditPropertyRequestForm" method="POST" action="{% url 'RealEstate_admin:addEditPropertyRequest' %}">
	{% csrf_token %}
	<input type="hidden" value="{{property_request.id}}" name="property_request_id" />
	    <div class="row">
                  <div class="col-md-6">
                      <div class="form-group">
                          <label for="name" class="col-sm-4 control-label">نام</label>
                          <div class="col-sm-8">
                              <input type="text" class="form-control" id="name" name="name"  value="{{property_request.name}}">
                          </div>
                      </div>
                  </div>
                  <div class="col-md-6">
                      <div class="form-group">
                          <label for="family" class="col-sm-4 control-label">نام خانوادگی</label>
                          <div class="col-sm-8">
                              <input type="text" class="form-control" id="family" name="family"  			value="{{property_request.family}}">
                          </div>
                      </div>
                  </div>
              </div>
          
	    <div class="row">
                  <div class="col-md-6">
                      <div class="form-group">
                          <label for="phone_no" class="col-sm-4 control-label">شماره تماس</label>
                          <div class="col-sm-8">
                              <input type="text" class="form-control" id="phone_no" name="phone_no"  value="{{property_request.phone_no}}">
                          </div>
                      </div>
                  </div>
		  <div class="col-md-6">
                          <div class="form-group">
                <label for="deal_type" class="col-sm-4 control-label">نوع معامله مورد درخواست</label>
                <div class="col-sm-8">
                    <select class="form-control" name="deal_type" id="deal_type">
        		{{ property_request | format_request_deal_type | safe }} 
                    </select>
                </div>
            </div>
        </div>          
	
	   <div class="row">
              <div class="col-md-6">
                          <div class="form-group">
                <label for="property_type" class="col-sm-4 control-label">نوع ملک مورد درخواست</label>
                <div class="col-sm-8">
                    <select class="form-control" name="property_type" id="property_type">
        		{{ property_request | format_request_property_type | safe }} 
                    </select>
                </div>
            </div>
              </div> 
              <div class="col-md-6">
                  
            <div class="form-group  hidden" id="OtherPropertyTypeGroup">
                <label for="other_property_type_name" class="col-sm-4 control-label ">سایر</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="other_property_type_name" name="other_property_type_name" value="{{property_request.other_property_type_name|default_if_none:''}}">
                </div>
            </div>

              </div>
          </div>

 <div class="row">
            <div class="col-md-6">
                      <div class="form-group">
                          <label for="total_price" class="col-sm-4 control-label">قیمت کل مورد نظر برای خرید</label>
                          <div class="col-sm-8">
                              <input type="text" class="form-control" id="total_price" name="total_price"  			value="{{property_request.total_price|default_if_none:''}}">
                          </div>
                      </div>
                  </div>
              

		<div class="col-md-6">
                      <div class="form-group">
                          <label for="rahne_kamel_price" class="col-sm-4 control-label">رهن کامل</label>
                          <div class="col-sm-8">
                              <input type="text" class="form-control" id="rahne_kamel_price" name="rahne_kamel_price"  			value="{{property_request.rahne_kamel_price|default_if_none:''}}">
                          </div>
                      </div>
                  </div>
              </div>
              
          

 <div class="row">
            <div class="col-md-6">
                      <div class="form-group">
                          <label for="rahn_price" class="col-sm-4 control-label">رهن</label>
                          <div class="col-sm-8">
                              <input type="text" class="form-control" id="rahn_price" name="rahn_price"  			value="{{property_request.rahn_price|default_if_none:''}}">
                          </div>
                      </div>
                  </div>
              

		<div class="col-md-6">
                      <div class="form-group">
                          <label for="ejare_price" class="col-sm-4 control-label">اجاره</label>
                          <div class="col-sm-8">
                              <input type="text" class="form-control" id="ejare_price" name="ejare_price"  			value="{{property_request.ejare_price|default_if_none:''}}">
                          </div>
                      </div>
                  </div>
              </div>
              
              
              <div class="row">
            <div class="col-md-6">
                      <div class="form-group">
                          <label for="area" class="col-sm-4 control-label">محدوده</label>
                          <div class="col-sm-8">
                              <input type="text" class="form-control" id="area" name="area" value="{{property_request.area|default_if_none:''}}">
                          </div>
                      </div>
                  </div>
              

		<div class="col-md-6">
                      <div class="form-group">
                          <label for="description" class="col-sm-4 control-label">توضیحات</label>
                          <div class="col-sm-8">
                           <textarea class="form-control" name="description" id="description">{{property_request.description|default_if_none:''}}</textarea>                            
                          </div>
                      </div>
                  </div>
              </div>
              
              
        
 <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">ثبت درخواست</button>
                </div>
            </div>
          </div>
</form>
<div class="control-group" style="float:left;">
                <div class="col-sm-offset-2 col-sm-10">
                    <a href="{% url 'RealEstate_admin:propertyRequests'%}">
<button class="btn btn-primary">بازگشت به مدیریت درخواستها</button>
</a>
                </div>
            </div>


{% endblock %}

RealEstate/RealEstate_admin/templates/RealEstate_admin/request/index.html
{% extends "Luna_admin/admin_master.html" %}
{% load staticfiles %}
{% load luna_filters %}
{% block page_title %}{% block content_title %}مدیریت درخواستها{% endblock %}{% endblock %}
{% block body_script %}
	<script  src="{% static 'Luna_admin/script/validate.js' %}"></script>
{% endblock %}
{% block content %}

        {% comment %}جستجو{% endcomment %}
        <div class="thumbnail">

    <form class="form-inline" role="form" method="GET" action="{% url 'RealEstate_admin:propertyRequests' %}" >
        <div class="form-group">
            <input type="text" class="form-control input-sm" id="fullname"  name="fullname" placeholder="نام یا نام خانوادگی مالک" value="{{fullname}}">
        </div>
        <div class="form-group">
            <input type="text" class="form-control input-sm" id="area" name="area" placeholder="محدوده" value="{{area}}">
        </div>

        <div class="form-group">
             <select class="form-control" name="property_type" id="property_type">
                                  <option value="">---</option>
                                  <option value="apartment" {%ifequal property_type 'apartment'%}selected{%endifequal%}>آپارتمان</option>
                                  <option value="house" {%ifequal property_type 'house'%}selected{%endifequal%}>خانه( دربست ، طبقه ، کلنگی)</option>
                                  <option value="suite" {%ifequal property_type 'suite'%}selected{%endifequal%}>سوئیت (خانه ، آپارتمان)</option>
                                  <option value="shop" {%ifequal property_type 'shop'%}selected{%endifequal%}>مغازه</option>
                              </select>
        </div>
        <div class="form-group">
         <select class="form-control" id="deal_type" name="deal_type">
                        <option value="">---</option>
                        <option value="rahn_va_ejare" {%ifequal deal_type 'rahn_va_ejare'%}selected{%endifequal%}>رهن واجاره</option>
                        <option value="rahn_kamel" {%ifequal deal_type 'rahn_kamel'%}selected{%endifequal%}>رهن کامل</option>
                        <option value="forush_malekiyat" {%ifequal deal_type 'forush_malekiyat'%}selected{%endifequal%}>فروش مالکیت</option>
                        <option value="forush_sarghofly" {%ifequal deal_type 'forush_sarghofly'%}selected{%endifequal%}>فروش سرقفلی</option>
                        <option value="moaveze" {%ifequal deal_type 'moaveze'%}selected{%endifequal%}>معاوضه</option>
                        <option value="pish_forush" {%ifequal deal_type 'pish_forush'%}selected{%endifequal%}>پیش فروش</option>
                        <option value="mosharekat_dar_sakht" {%ifequal deal_type 'mosharekat_dar_sakht'%}selected{%endifequal%}>مشارکت در ساخت</option>
                    </select>
         </div>
        <div class="form-group">
        <button type="submit" class="btn btn-primary btn-sm">جستجوی درخواست</button></div>
    </form>

</div>


<div class="thumbnail">
	{% if not property_requests %}
		<p class="notFind"><span class="glyphicon glyphicon-minus"></span>درخواستی ثبت نشده است</p>
	{% else %}
        <table class="table table-responsive table-striped table-hover">
            <thead>
                <tr><td>تاریخ ثبت</td><td>نام و نام خانوادگی درخواست کننده</td><td>شماره تماس</td>
                    <td>نوع معامله</td><td>نوع ملک</td> <td>محدوده</td>
                <td>خرید</td><td>رهن کامل</td> <td>رهن</td>  <td>اجاره</td><td>توضیحات دارد؟</td> 
                 <td>ویرایش</td><td>حذف</td>
                </tr>
            </thead>
            <tbody>
			{% for property_request in property_requests %}
			  <tr>
               <td>{{property_request.creation_date| persian_date}}</td>
			   <td style="text-align:center;">{{property_request.name}} {{property_request.family}}</td>
               <td>{{property_request.phone_no}}</td>
                   <td>{{property_request| format_deal_type | safe}}</td>
			   <td>{{property_request| format_property_type | safe}}</td>
			   <td>{{property_request.area|default_if_none:''}}</td>
			   <td>{{property_request.total_price|default_if_none:''}}</td>
			   <td>{{property_request.rahne_kamel_price|default_if_none:''}}</td>
			   <td>{{property_request.rahn_price|default_if_none:''}}</td>
			   <td>{{property_request.ejare_price|default_if_none:''}}</td>
			   <td style="text-align:center;">
                   {% if property_request.description %}
                   <span class="glyphicon glyphicon-ok"></span>
			     {% else %}
			     <span class="glyphicon glyphicon-remove"></span>
			     {% endif %}
			   </td>

			 

			  <td> <a href="../admin/add_edit_request/{{ property_request.id }}/"><span class="glyphicon glyphicon-floppy-saved"></span></a></td>
              <td> <a href="{% url 'RealEstate_admin:deletePropertyRequest' property_request.id %}"><span class="glyphicon glyphicon-trash"></span></a></td></tr>
			{% endfor %}
            </tbody>
        </table>
  <ul class="pagination">
		 {% if property_requests.has_previous %}
			<li><a href="?page={{ property_requests.previous_page_number }}"><</a></li>
        {% endif %}

        <li class="active"><a href=#>
            صفحه {{ property_requests.number }} از {{ property_requests.paginator.num_pages }}
        </a></li>

        {% if property_requests.has_next %}
            <li><a href="?page={{ property_requests.next_page_number }}">></a></li>
        {% endif %}
       
</ul>
	{% endif %}

</div>
{% comment %} ثبت درخواست جدید{% endcomment %}
 
<div class="">
  <a href="{% url 'RealEstate_admin:addEditPropertyRequest' %}">
    <button type="button" class="btn btn-primary btn-sm "><span class="glyphicon glyphicon-plus"></span>ثبت درخواست جدید</button>
   </a>
</div>






{% endblock %}